### ISSUE TITLE
counter++ ?

### ISSUE THREAD

**Issue by pierrebressy** [imapanda/arduino-nano#1]
option 1 :     

counter = 1-counter;  // 0, 1, 0, 1 etc.

option 2 : 

counter++;

in the loop function:

if(counter&1) { display_temp(); }
else { display_humidity(); }

**Comment by imapanda** [comment]
### option 1 :

`counter = 1-counter; // 0, 1, 0, 1 etc.`

### option 2 :

`counter++;`

in the loop function:

```
if(counter&1) { display_temp(); }
else { display_humidity(); }
```

**Comment by pierrebressy** [comment]
```C
void displayTemp() {
    puts("T=xxx °C");
    return;
}

void displayHumidity() {
    puts("H=XXX %");
    return;
}

int main(int argc, char const *argv[])
{
    void (*functions[2])(void) = {displayTemp,displayHumidity};

    int counter = 0;

    for (counter = 0; counter < 5;counter++) {
        functions[counter&1]();
    }
    return 0;
}

```

**Comment by imapanda** [comment]
> ```c
> void displayTemp() {
>     puts("T=xxx °C");
>     return;
> }
> 
> void displayHumidity() {
>     puts("H=XXX %");
>     return;
> }
> 
> int main(int argc, char const *argv[])
> {
>     void (*functions[2])(void) = {displayTemp,displayHumidity};
> 
>     int counter = 0;
> 
>     for (counter = 0; counter < 5;counter++) {
>         functions[counter&1]();
>     }
>     return 0;
> }
> ```

Used this solution
